#define CFC_TOKENTYPE_FILE_START                      1
#define CFC_TOKENTYPE_SEMICOLON                       2
#define CFC_TOKENTYPE_RIGHT_CURLY_BRACE               3
#define CFC_TOKENTYPE_CLASS                           4
#define CFC_TOKENTYPE_COLON                           5
#define CFC_TOKENTYPE_IDENTIFIER                      6
#define CFC_TOKENTYPE_LEFT_CURLY_BRACE                7
#define CFC_TOKENTYPE_VOID                            8
#define CFC_TOKENTYPE_VA_LIST                         9
#define CFC_TOKENTYPE_INTEGER_TYPE_NAME              10
#define CFC_TOKENTYPE_FLOAT_TYPE_NAME                11
#define CFC_TOKENTYPE_PUBLIC                         12
#define CFC_TOKENTYPE_PRIVATE                        13
#define CFC_TOKENTYPE_PARCEL                         14
#define CFC_TOKENTYPE_LOCAL                          15
#define CFC_TOKENTYPE_CONST                          16
#define CFC_TOKENTYPE_NULLABLE                       17
#define CFC_TOKENTYPE_INCREMENTED                    18
#define CFC_TOKENTYPE_DECREMENTED                    19
#define CFC_TOKENTYPE_INERT                          20
#define CFC_TOKENTYPE_INLINE                         21
#define CFC_TOKENTYPE_ABSTRACT                       22
#define CFC_TOKENTYPE_FINAL                          23
#define CFC_TOKENTYPE_ASTERISK                       24
#define CFC_TOKENTYPE_LEFT_SQUARE_BRACKET            25
#define CFC_TOKENTYPE_RIGHT_SQUARE_BRACKET           26
#define CFC_TOKENTYPE_INTEGER_LITERAL                27
#define CFC_TOKENTYPE_HEX_LITERAL                    28
#define CFC_TOKENTYPE_FLOAT_LITERAL                  29
#define CFC_TOKENTYPE_STRING_LITERAL                 30
#define CFC_TOKENTYPE_TRUE                           31
#define CFC_TOKENTYPE_FALSE                          32
#define CFC_TOKENTYPE_NULL                           33
#define CFC_TOKENTYPE_LEFT_PAREN                     34
#define CFC_TOKENTYPE_RIGHT_PAREN                    35
#define CFC_TOKENTYPE_COMMA                          36
#define CFC_TOKENTYPE_ELLIPSIS                       37
#define CFC_TOKENTYPE_EQUALS                         38
#define CFC_TOKENTYPE_SCOPE_OP                       39
#define CFC_TOKENTYPE_DOCUCOMMENT                    40
#define CFC_TOKENTYPE_INHERITS                       41
#define CFC_TOKENTYPE_CNICK                          42
#define CFC_TOKENTYPE_CBLOCK_START                   43
#define CFC_TOKENTYPE_CBLOCK_CLOSE                   44
#define CFC_TOKENTYPE_BLOB                           45
